- name : loops in ansible
  hosts : localhost 
  tasks :
  - name : loops 
    ansible.builtin.debug:
     msg : "Hi {{item}}"
    loop :
    - shell
    - ansible
    - linux 



- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
    - mysql
    - nginx
    - postfix



- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'latest'} # item
    - { name: 'nginx', state: 'absent'}
    - { name: 'postfix', state: 'absent'}