- name : variable preferences
  hosts : localhost
  vars:
   WHISHES : good morning from play vars

  vars_files : 
  - vars.yaml
  
  vars_prompt :
  - name : WISHES
    prompt : please enter var value
    private : false

  tasks :
  - name: vars from task
    vars :
      WISHES : "Good Morning" 
    ansible.builtin.debug:
     msg : Good {{WISHES}}



     
# 1. arguments
# 2. Task level
# 3. variable files
# 4. Prompt
# 5. Play level
# 6. inventory
# 7. role level
  
