- name : variable preferences
  hosts : localhost
  vars:
   WHISHES : good morning from play vars

  vars_files : 
  - vars.yaml
  
  vars_prompt :
  - name : WISHES
    prompt : please enter var value
    private : false

  tasks :
  - name: vars from task
    vars :
      WISHES : "Good Morning" 
    ansible.builtin.debug:
     msg : Good {{WISHES}}
  
