- name : vars from prompt
  hosts : localhost
  vars_prompt :
    - name : USERNAME 
      prompt : "please enter your name here :"
      private : false
    - name : PASSWORD
      prompt : "please enter your password here : "
      private : true
    tasks :
    - name : print information
      ansible.builtin.debug:
        msg : Hi User name is {{USERNAME}} , Password is {{PASSWORD}}


